version: "3"

volumes:
  db_data_local: {}

services:
  db:
    image: postgres
    container_name: blog__database
    volumes:
      - db_data_local:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - private_network
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: blog__web
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - private_network
    command: python manage.py runserver 0.0.0.0:8000

networks:
  private_network:
    driver: bridge